name: kindred_app
description: ""
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3

scripts:
  clean: fvm flutter clean
  pub-get: fvm flutter pub get
  version:
    install: fvm install 3.24.3
    set: fvm use 3.24.3
  gen-intl: fvm dart run intl_utils:generate
  launch:
    dev: fvm flutter run -d chrome --dart-define-from-file=".secrets/dev.json"
    stg: fvm flutter run -d chrome --dart-define-from-file=".secrets/stg.json"
    prod: fvm flutter run -d chrome --dart-define-from-file=".secrets/prod.json"
  build:
    apk:
      dev: fvm flutter build apk --release --dart-define-from-file=".secrets/dev.json"
      stg: fvm flutter build apk --release --dart-define-from-file=".secrets/stg.json"
      prod: fvm flutter build apk --release --dart-define-from-file=".secrets/stg.json"
    aab:
      dev: fvm flutter build appbundle --dart-define-from-file=".secrets/dev.json"
      stg: fvm flutter build appbundle --dart-define-from-file=".secrets/stg.json"
      prod: fvm flutter build appbundle --dart-define-from-file=".secrets/prod.json"


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  go_router: ^14.6.0
  retrofit: ^4.4.1
  logger: ^2.4.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  responsive_sizer: ^3.3.1
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Louize
      fonts:
        - asset: assets/fonts/Louize.ttf
    - family: GTWalsheimPro
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Regular.ttf

flutter_intl:
  enabled: true
  class_name: Lang
  arb_dir: lib/common/translations
  output_dir: lib/common/translations/generated

flutter_gen:
  output: lib/common/resources
  line_length: 120