name: kindred_mobile
description: ""
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  auto_mappr_annotation: ^2.2.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  equatable: ^2.0.5
  get_it: ^7.6.4
  go_router: ^14.6.0
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  retrofit: ^4.4.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  meta: ^1.15.0
 
  cupertino_icons: ^1.0.8
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.5.0
  auto_mappr: ^2.5.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  injectable_generator: ^2.6.2
  intl_utils: ^2.8.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.5
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  fonts:
  - family: GTWalsheim
    fonts:
      - asset: assets/fonts/GTWalsheimPro-Regular.ttf
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: Lang
  arb_dir: lib/common/translations
  output_dir: lib/common/translations/generated

flutter_gen:
  output: lib/common/resources
  line_length: 120